apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace : argo-cd  
spec:
  project: default
  source:
    repoURL: git@github.com:hyperique/finalproject.git
    targetRevision: HEAD
    path: 'app/helm-chart'
    helm:
      valueFiles:
        - values.yaml
  destination:    
    server: https://10.10.35.10:6443
    namespace: demo
  sources: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true