apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demoshop
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "demoshop"
  scopedRepos:
  - 'git@github.com:hyperique/finalproject.git'
  destinations:
  - namespace: 'demo'
    server: https://10.10.35.10:6443
    name: kubernetes-admin@ust.local
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'