apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor-hdd-external-storage
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  linstor.csi.linbit.com/storagePool: "linstor-pool-hdd-all"