apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume
spec:
  storageClassName: linstor-csi-lvm-thin-ssd
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce