name: Setup Kubernetes Cluster

on:
  workflow_dispatch:  # Ручной запуск через интерфейс GitHub

jobs:
  setup-cluster:
    runs-on: ubuntu-latest

    steps:
    - name: Install Prerequisites
      run: |
        sudo apt-get update
        sudo add-apt-repository -y ppa:deadsnakes/ppa
        sudo apt-get update
        sudo apt-get install -y python3.10 python3.10-distutils python3.10-venv python3-pip

    - name: Install Virtualenv
      run: pip3 install --user virtualenv

    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Connect to Server and Setup Cluster
      run: |
        ssh -o StrictHostKeyChecking=no -p 55522 k8s@93.85.93.70 << 'EOF'
          # Настройка Virtual Environment для Python
          python3.10 -m venv ~/envs/kubespray
          source ~/envs/kubespray/bin/activate

          # Установка Ansible и необходимых пакетов в виртуальном окружении
          echo -e 'ansible==9.11.0\njmespath==1.0.1\njsonschema==4.23.0\nnetaddr==1.3.0' > ~/requirements.txt
          pip install -r ~/requirements.txt
          pip install ruamel.yaml

          # Установка коллекции ansible.posix для работы с systemd
          ansible-galaxy collection install ansible.posix

          # Переход в директорию с уже клонированным репозиторием Kubespray
          cd ~/kubespay

          if [ -d "inventory/sample" ]; then
            cp -rfp inventory/sample inventory/mycluster
          fi
           #использование уже существующего hosts.yaml
          #declare -a IPS=(10.10.35.61 10.10.35.63)
          #CONFIG_FILE=inventory/mycluster/hosts.yaml python3.10 contrib/inventory_builder/inventory.py ${IPS[@]}

         
          # Выполнение Ansible Playbook
          if [ -f "inventory/mycluster/hostsbck.yaml" ]; then
            ansible-playbook -i inventory/mycluster/hosts.yaml --become-user=root cluster.yml \
              -e ansible_user=root \
              -e ansible_ssh_private_key_file=/home/k8s/.ssh/id_rsa
            deactivate
          fi
          deactivate
        EOF

    - name: Clean up
      run: echo "Kubernetes cluster setup completed."
