name: Setup Kubernetes Cluster

on:
  workflow_dispatch:  # Ручной запуск через интерфейс GitHub

jobs:
  setup-cluster:
    runs-on: ubuntu-latest

    steps:
    - name: Install Prerequisites
      run: sudo apt-get update && sudo apt-get install -y python3-pip sshpass

    - name: Install Ansible and Other Dependencies
      run: |
        pip3 install ansible==5.2.0  # Версию Ansible можно менять при необходимости
        pip3 install jinja2 netaddr

    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Connect to Server and Setup Cluster
      run: |
        ssh -o StrictHostKeyChecking=no -p 55522 k8s@93.85.93.70 << 'EOF'
          # Клонирование репозитория Kubespray
          git clone https://github.com/kubernetes-sigs/kubespray.git ~/testcluster
          cd ~/testcluster

          # Настройка инвентаря
          cp -rfp inventory/sample inventory/mycluster
          declare -a IPS=(10.10.35.61 10.10.35.63)
          CONFIG_FILE=inventory/mycluster/hosts.yaml python3 contrib/inventory_builder/inventory.py ${IPS[@]}

          # Обновление Ansible инвентаря для использования пользователя 'it'
          sed -i 's/ansible_user: root/ansible_user: it/g' inventory/mycluster/hosts.yaml

          # Запуск Ansible Playbook
          ansible-playbook -i inventory/mycluster/hosts.yaml --become --become-user=root cluster.yml
        EOF

    - name: Clean up
      run: echo "Kubernetes cluster setup completed."
